name: 'Kỳ thi thử cho K64 - Beyond the Dawn'
enable: true
news:
  title: 'THAM GIA THI THỬ CÙNG SITDE PK'
  description: 'Các kỳ thi thử sẽ được diễn ra định kỳ theo lịch thi trên trường. Hay follow fanpage fb.com/sitdepk ngay hôm nay để nắm bắt kịp thời những thông tin về các kỳ thi thử.'
  url: 'https://facebook.com/sitdepk'
data:
  KHMA1101:
    name: 'Kinh tế vĩ mô'
    time: 3600
    noQuestion: 40
    testing: false
    password: '22779'
    sessions:
      '01/10/2023':
        - '15:00 - 20:00'
        - '22:00 - 23:30'
