enable: true
name: 'Kỳ thi thử cho K65 - Outstanding'
news:
  title: 'BE BRAVE - BE OUTSTANDING'
  description: 'Kỳ thi thử dành cho K65 Outstanding trên SITDE PK đang được khởi động. Hãy truy cập fb.com/sitdepk ngay để nắm bắt kịp thời những thông tin về kỳ thi thử này.'
  url: 'https://facebook.com/sitdepk'
  image: 'OUTSTANDING.jpg'
data:
  TOCB1107:
    name: 'Toán rời rạc'
    time: 3600
    noQuestion: 40
    testing: false
    password: '37750'
    sessions:
      '14/01/2024':
        - '09:00 - 10:00'
        - '13:00 - 14:00'
        - '20:30 - 21:30'
  CNTT1116:
    name: 'Nhập môn Công nghệ thông tin'
    time: 3600
    noQuestion: 40
    testing: false
    password: '63412'
    sessions:
      '14/01/2024':
        - '07:00 - 08:00'
        - '08:30 - 09:30'
        - '10:00 - 11:30'
  QLKT1101:
    name: 'Quản lý học'
    time: 3600
    noQuestion: 40
    testing: false
    password: '55983'
    sessions:
      '14/01/2024':
        - '13:00 - 14:00'
        - '14:30 - 15:30'
        - '16:00 - 17:00'
        - '21:00 - 22:00'
  KHMI1101:
    name: 'Kinh tế vi mô'
    time: 3600
    noQuestion: 40
    testing: false
    password: '11205'
    sessions:
      '15/01/2024':
        - '08:30 - 09:30'
        - '10:00 - 11:00'
        - '14:30 - 15:30'
        - '20:00 - 21:00'
      '16/01/2024':
        - '08:30 - 09:30'
        - '10:00 - 11:00'
        - '14:30 - 15:30'
        - '20:00 - 21:00'
  KHMA1101:
    name: 'Kinh tế vĩ mô'
    time: 3600
    noQuestion: 40
    testing: false
    password: '23507'
    sessions:
      '15/01/2024':
        - '07:00 - 08:00'
        - '13:00 - 14:00'
        - '16:00 - 17:00'
        - '21:00 - 22:00'
      '16/01/2024':
        - '07:00 - 08:00'
        - '13:00 - 14:00'
        - '16:00 - 17:00'
        - '21:00 - 22:00'
  LUCS1129:
    name: 'Pháp luật đại cương'
    time: 3600
    noQuestion: 40
    testing: false
    password: '77231'
    sessions:
      '21/01/2024':
        - '13:00 - 14:00'
        - '14:30 - 15:30'
        - '20:00 - 21:00'
  LLNL1105:
    name: 'Triết học Mác - Lênin'
    time: 3600
    noQuestion: 80
    testing: false
    password: '64931'
    sessions:
      '21/01/2024':
        - '07:00 - 08:00'
        - '08:30 - 09:30'
        - '16:00 - 17:00'
        - '21:00 - 22:00'
  TOCB1101:
    name: 'Đại số'
    time: 3600
    noQuestion: 40
    testing: false
    password: '52349'
    sessions:
      '25/01/2024':
        - '14:30 - 15:30'
        - '16:00 - 17:00'
        - '21:00 - 22:00'
  TIHT1102:
    name: 'Hệ thống thông tin quản lý'
    time: 3600
    noQuestion: 40
    testing: false
    password: '78522'
    sessions:
      '25/01/2024':
        - '10:00 - 11:00'
        - '18:00 - 19:00'
        - '19:30 - 20:30'
  CNTT1191:
    name: 'Vật lý đại cương'
    time: 3600
    noQuestion: 40
    testing: false
    password: '02851'
    sessions:
      '25/01/2024':
        - '07:00 - 08:00'
        - '08:30 - 09:30'
        - '10:00 - 11:00'
        - '14:30 - 15:30'
