enable: true
name: 'Kỳ thi thử cho K65 - Quantum Leap'
news:
  title: 'BỨT PHÁ KHÔNG GIỚI HẠN QUANTUM LEAP'
  description: 'Kỳ thi thử dành cho K65 Quantum Leap trên SITDE PK đã bắt đầu. Hãy truy cập fb.com/sitdepk ngay để nắm bắt những thông tin về kỳ thi thử này.'
  url: 'https://facebook.com/sitdepk'
  image: 'QUANTUMLEAP.png'
data:
  CNTT1128:
    hasExplanation: false
    name: 'Cơ sở lập trình'
    time: 3600
    noQuestion: 40
    testing: false
    password: '1128'
    sessions:
      '01/07/2024':
        - '08:00 - 09:00'
        - '10:30 - 11:30'
        - '14:00 - 15:00'
        - '16:00 - 17:00'
        - '20:00 - 21:00'
        - '22:00 - 23:00'
  KHMA1101:
    hasExplanation: false
    name: 'Kinh tế vĩ mô'
    time: 3600
    noQuestion: 40
    testing: false
    password: '1101'
    sessions:
      '03/07/2024':
        - '08:00 - 09:00'
        - '10:30 - 11:30'
        - '14:00 - 15:00'
        - '16:00 - 17:00'
        - '20:00 - 21:00'
        - '22:00 - 23:00'
  KHMI1101:
    hasExplanation: false
    name: 'Kinh tế vi mô'
    time: 3600
    noQuestion: 40
    testing: false
    password: '1102'
    sessions:
      '04/07/2024':
        - '08:00 - 09:00'
        - '10:30 - 11:30'
        - '14:00 - 15:00'
        - '16:00 - 17:00'
        - '20:00 - 21:00'
        - '22:00 - 23:00'
  LLNL1105:
    hasExplanation: false
    name: 'Triết học Mác - Lênin'
    time: 3000
    noQuestion: 80
    testing: false
    password: '1105'
    sessions:
      '05/07/2024':
        - '08:00 - 09:00'
        - '10:30 - 11:30'
        - '14:00 - 15:00'
        - '16:00 - 17:00'
        - '20:00 - 21:00'
        - '22:00 - 23:00'
  LLNL1106:
    hasExplanation: false
    name: 'Kinh tế chính trị Mác - Lênin'
    time: 3000
    noQuestion: 80
    testing: false
    password: '1106'
    sessions:
      '06/07/2024':
        - '08:00 - 09:00'
        - '10:30 - 11:30'
        - '14:30 - 15:30'
        - '16:00 - 17:00'
        - '20:00 - 21:00'
        - '22:00 - 23:00'
  QLKT1101:
    hasExplanation: false
    name: 'Quản lý học'
    time: 3600
    noQuestion: 40
    testing: false
    password: '1101'
    sessions:
      '08/07/2024':
        - '08:00 - 09:00'
        - '10:30 - 11:30'
        - '14:00 - 15:00'
        - '16:00 - 17:00'
        - '20:00 - 21:00'
        - '22:00 - 23:00'
  TOKT1145:
    hasExplanation: false
    name: 'Lý thuyết xác suất và thống kê Toán'
    time: 3600
    noQuestion: 40
    testing: false
    password: '1145'
    sessions:
      '09/07/2024':
        - '08:00 - 09:00'
        - '10:30 - 11:30'
        - '14:00 - 15:00'
        - '16:00 - 17:00'
        - '20:00 - 21:00'
        - '22:00 - 23:00'
  LUCS1129:
    hasExplanation: false
    name: 'Pháp luật đại cương'
    time: 3000
    noQuestion: 80
    testing: false
    password: '1129'
    sessions:
      '10/07/2024':
        - '08:00 - 09:00'
        - '10:30 - 11:30'
        - '14:00 - 15:00'
        - '16:00 - 17:00'
        - '20:00 - 21:00'
        - '22:00 - 23:00'
  CNTT1182:
    hasExplanation: false
    name: 'Phương pháp tính'
    time: 3600
    noQuestion: 30
    testing: false
    password: '1182'
    sessions:
      '12/07/2024':
        - '08:00 - 09:00'
        - '10:30 - 11:30'
        - '14:00 - 15:00'
        - '16:00 - 17:00'
        - '20:00 - 21:00'
        - '22:00 - 23:00'
  TIHT1102:
    hasExplanation: false
    name: 'Hệ thống thông tin quản lý'
    time: 3600
    noQuestion: 40
    testing: false
    password: '1102'
    sessions:
      '13/07/2024':
        - '08:00 - 09:00'
        - '10:30 - 11:30'
        - '14:00 - 15:00'
        - '16:00 - 17:00'
        - '20:00 - 21:00'
        - '22:00 - 23:00'
      '14/07/2024':
        - '10:30 - 11:30'
