enable: true
name: 'Kỳ thi thử cho K65 - Quantum Leap'
news:
  title: 'BỨT PHÁ KHÔNG GIỚI HẠN QUANTUM LEAP'
  description: 'Kỳ thi thử dành cho K65 Quantum Leap trên SITDE PK đã bắt đầu. Hãy truy cập fb.com/sitdepk ngay để nắm bắt những thông tin về kỳ thi thử này.'
  url: 'https://facebook.com/sitdepk'
  image: 'QUANTUMLEAP.png'
data:
  KHMA1101:
    hasExplanation: false
    name: 'Kinh tế vĩ mô'
    time: 3600
    noQuestion: 40
    testing: false
    password: '1101'
    sessions:
      '05/06/2025':
        - '12:10 - 14:00'
